declare const styles: {
  readonly "calculator": string;
  readonly "criterionName": string;
  readonly "criterionRow": string;
  readonly "gridDescription": string;
  readonly "gridLabel": string;
  readonly "gridRow": string;
  readonly "gridSelect": string;
  readonly "page": string;
  readonly "resetBtn": string;
  readonly "scoreActions": string;
  readonly "scoreBar": string;
  readonly "scoreDisplay": string;
  readonly "scoreMain": string;
  readonly "scoreRaw": string;
  readonly "scoreSuffix": string;
  readonly "section": string;
  readonly "sectionBody": string;
  readonly "sectionCount": string;
  readonly "sectionCountComplete": string;
  readonly "sectionHeader": string;
  readonly "sectionTitle": string;
  readonly "stepBtn": string;
  readonly "stepBtnSelected": string;
  readonly "stepButtons": string;
  readonly "stepDesc": string;
  readonly "stepLabel": string;
};
export = styles;

