declare const styles: {
  readonly "areaBox": string;
  readonly "areaGroups": string;
  readonly "areaSource": string;
  readonly "body": string;
  readonly "bulk": string;
  readonly "bulkAdd": string;
  readonly "bulkBtn": string;
  readonly "bulkCount": string;
  readonly "excluded": string;
  readonly "excludedEmpty": string;
  readonly "excludedHead": string;
  readonly "indexCount": string;
  readonly "indexEmpty": string;
  readonly "indexList": string;
  readonly "indexName": string;
  readonly "indexRow": string;
  readonly "newGroup": string;
  readonly "note": string;
  readonly "nudge": string;
  readonly "nudgeYes": string;
  readonly "nudges": string;
  readonly "others": string;
  readonly "othersHead": string;
  readonly "panes": string;
  readonly "picker": string;
  readonly "rail": string;
  readonly "sort": string;
  readonly "sortLabel": string;
  readonly "sortSelect": string;
  readonly "wrap": string;
};
export = styles;

